# Generated by Django 5.2 on 2025-04-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='company',
            field=models.CharField(default='TestCompany', max_length=255),
            preserve_default=False,
        ),
    ]
