# Generated by Django 5.2 on 2025-04-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_joblisting_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='suggestions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
