# Generated by Django 5.2 on 2025-04-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_application_suggestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='match_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
